/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CardType = IDL.Variant({
  'trap' : IDL.Null,
  'spell' : IDL.Null,
  'monster' : IDL.Record({
    'xyz' : IDL.Bool,
    'link' : IDL.Bool,
    'ritual' : IDL.Bool,
    'effect' : IDL.Bool,
    'fusion' : IDL.Bool,
    'synchro' : IDL.Bool,
  }),
});
export const Attribute = IDL.Variant({
  'dark' : IDL.Null,
  'fire' : IDL.Null,
  'wind' : IDL.Null,
  'earth' : IDL.Null,
  'light' : IDL.Null,
  'divine' : IDL.Null,
  'water' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'atk' : IDL.Opt(IDL.Nat),
  'def' : IDL.Opt(IDL.Nat),
  'monster_type' : IDL.Opt(IDL.Text),
  'owner' : IDL.Opt(IDL.Principal),
  'summon_sound' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'level_rank' : IDL.Opt(IDL.Nat),
  'attack_sound' : IDL.Opt(ExternalBlob),
  'art_blob' : IDL.Opt(ExternalBlob),
  'effect_text' : IDL.Opt(IDL.Text),
  'effect_sound' : IDL.Opt(ExternalBlob),
  'rarity' : IDL.Nat,
  'card_type' : CardType,
  'is_custom' : IDL.Bool,
  'attribute' : IDL.Opt(Attribute),
});
export const DuelAction = IDL.Record({
  'action_type' : IDL.Text,
  'details' : IDL.Text,
});
export const DuelHistory = IDL.Record({
  'winner' : IDL.Principal,
  'actions' : IDL.Vec(DuelAction),
  'player1' : IDL.Principal,
  'player2' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfileView = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'wallpaper' : IDL.Text,
  'profile_picture' : IDL.Opt(ExternalBlob),
  'difficulty' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'level' : IDL.Nat,
  'pack_count' : IDL.Nat,
});
export const CustomSound = IDL.Record({
  'victory_sound' : IDL.Opt(ExternalBlob),
  'summon_sound' : IDL.Opt(ExternalBlob),
  'attack_sound' : IDL.Opt(ExternalBlob),
  'defeat_sound' : IDL.Opt(ExternalBlob),
  'effect_sound' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addUserCard' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomCard' : IDL.Func(
      [
        CardType,
        IDL.Opt(Attribute),
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [Card],
      [],
    ),
  'createDeck' : IDL.Func([IDL.Text], [], []),
  'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getAllDuelHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DuelHistory)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedDuelHistory' : IDL.Func([], [IDL.Vec(DuelHistory)], ['query']),
  'getCustomSounds' : IDL.Func([], [IDL.Vec(CustomSound)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'initDuel' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [
        IDL.Record({
          'duel_id' : IDL.Opt(IDL.Principal),
          'player1' : IDL.Principal,
        }),
      ],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(UserProfileView)],
      [],
    ),
  'takeTurn' : IDL.Func([IDL.Vec(DuelAction)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CardType = IDL.Variant({
    'trap' : IDL.Null,
    'spell' : IDL.Null,
    'monster' : IDL.Record({
      'xyz' : IDL.Bool,
      'link' : IDL.Bool,
      'ritual' : IDL.Bool,
      'effect' : IDL.Bool,
      'fusion' : IDL.Bool,
      'synchro' : IDL.Bool,
    }),
  });
  const Attribute = IDL.Variant({
    'dark' : IDL.Null,
    'fire' : IDL.Null,
    'wind' : IDL.Null,
    'earth' : IDL.Null,
    'light' : IDL.Null,
    'divine' : IDL.Null,
    'water' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'atk' : IDL.Opt(IDL.Nat),
    'def' : IDL.Opt(IDL.Nat),
    'monster_type' : IDL.Opt(IDL.Text),
    'owner' : IDL.Opt(IDL.Principal),
    'summon_sound' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'level_rank' : IDL.Opt(IDL.Nat),
    'attack_sound' : IDL.Opt(ExternalBlob),
    'art_blob' : IDL.Opt(ExternalBlob),
    'effect_text' : IDL.Opt(IDL.Text),
    'effect_sound' : IDL.Opt(ExternalBlob),
    'rarity' : IDL.Nat,
    'card_type' : CardType,
    'is_custom' : IDL.Bool,
    'attribute' : IDL.Opt(Attribute),
  });
  const DuelAction = IDL.Record({
    'action_type' : IDL.Text,
    'details' : IDL.Text,
  });
  const DuelHistory = IDL.Record({
    'winner' : IDL.Principal,
    'actions' : IDL.Vec(DuelAction),
    'player1' : IDL.Principal,
    'player2' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfileView = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'wallpaper' : IDL.Text,
    'profile_picture' : IDL.Opt(ExternalBlob),
    'difficulty' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'level' : IDL.Nat,
    'pack_count' : IDL.Nat,
  });
  const CustomSound = IDL.Record({
    'victory_sound' : IDL.Opt(ExternalBlob),
    'summon_sound' : IDL.Opt(ExternalBlob),
    'attack_sound' : IDL.Opt(ExternalBlob),
    'defeat_sound' : IDL.Opt(ExternalBlob),
    'effect_sound' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addUserCard' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomCard' : IDL.Func(
        [
          CardType,
          IDL.Opt(Attribute),
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [Card],
        [],
      ),
    'createDeck' : IDL.Func([IDL.Text], [], []),
    'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getAllDuelHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DuelHistory)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedDuelHistory' : IDL.Func([], [IDL.Vec(DuelHistory)], ['query']),
    'getCustomSounds' : IDL.Func([], [IDL.Vec(CustomSound)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'initDuel' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [
          IDL.Record({
            'duel_id' : IDL.Opt(IDL.Principal),
            'player1' : IDL.Principal,
          }),
        ],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfileView)],
        [],
      ),
    'takeTurn' : IDL.Func([IDL.Vec(DuelAction)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };