/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Attribute = { 'dark' : null } |
  { 'fire' : null } |
  { 'wind' : null } |
  { 'earth' : null } |
  { 'light' : null } |
  { 'divine' : null } |
  { 'water' : null };
export interface Card {
  'id' : bigint,
  'atk' : [] | [bigint],
  'def' : [] | [bigint],
  'monster_type' : [] | [string],
  'owner' : [] | [Principal],
  'summon_sound' : [] | [ExternalBlob],
  'name' : string,
  'level_rank' : [] | [bigint],
  'attack_sound' : [] | [ExternalBlob],
  'art_blob' : [] | [ExternalBlob],
  'effect_text' : [] | [string],
  'effect_sound' : [] | [ExternalBlob],
  'rarity' : bigint,
  'card_type' : CardType,
  'is_custom' : boolean,
  'attribute' : [] | [Attribute],
}
export type CardType = { 'trap' : null } |
  { 'spell' : null } |
  {
    'monster' : {
      'xyz' : boolean,
      'link' : boolean,
      'ritual' : boolean,
      'effect' : boolean,
      'fusion' : boolean,
      'synchro' : boolean,
    }
  };
export interface CustomSound {
  'victory_sound' : [] | [ExternalBlob],
  'summon_sound' : [] | [ExternalBlob],
  'attack_sound' : [] | [ExternalBlob],
  'defeat_sound' : [] | [ExternalBlob],
  'effect_sound' : [] | [ExternalBlob],
}
export interface DuelAction { 'action_type' : string, 'details' : string }
export interface DuelHistory {
  'winner' : Principal,
  'actions' : Array<DuelAction>,
  'player1' : Principal,
  'player2' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface UserProfileView {
  'xp' : bigint,
  'username' : string,
  'wallpaper' : string,
  'profile_picture' : [] | [ExternalBlob],
  'difficulty' : string,
  'wins' : bigint,
  'losses' : bigint,
  'level' : bigint,
  'pack_count' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addUserCard' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomCard' : ActorMethod<
    [
      CardType,
      [] | [Attribute],
      bigint,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    Card
  >,
  'createDeck' : ActorMethod<[string], undefined>,
  'getAllCards' : ActorMethod<[], Array<Card>>,
  'getAllDuelHistory' : ActorMethod<[Principal], Array<DuelHistory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedDuelHistory' : ActorMethod<[], Array<DuelHistory>>,
  'getCustomSounds' : ActorMethod<[], Array<CustomSound>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'initDuel' : ActorMethod<
    [[] | [Principal]],
    { 'duel_id' : [] | [Principal], 'player1' : Principal }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string],
    [] | [UserProfileView]
  >,
  'takeTurn' : ActorMethod<[Array<DuelAction>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];