/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Card {
    id: bigint;
    atk?: bigint;
    def?: bigint;
    monster_type?: string;
    owner?: Principal;
    summon_sound?: ExternalBlob;
    name: string;
    level_rank?: bigint;
    attack_sound?: ExternalBlob;
    art_blob?: ExternalBlob;
    effect_text?: string;
    effect_sound?: ExternalBlob;
    rarity: bigint;
    card_type: CardType;
    is_custom: boolean;
    attribute?: Attribute;
}
export interface CustomSound {
    victory_sound?: ExternalBlob;
    summon_sound?: ExternalBlob;
    attack_sound?: ExternalBlob;
    defeat_sound?: ExternalBlob;
    effect_sound?: ExternalBlob;
}
export type CardType = {
    __kind__: "trap";
    trap: null;
} | {
    __kind__: "spell";
    spell: null;
} | {
    __kind__: "monster";
    monster: {
        xyz: boolean;
        link: boolean;
        ritual: boolean;
        effect: boolean;
        fusion: boolean;
        synchro: boolean;
    };
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserProfileView {
    xp: bigint;
    username: string;
    wallpaper: string;
    profile_picture?: ExternalBlob;
    difficulty: string;
    wins: bigint;
    losses: bigint;
    level: bigint;
    pack_count: bigint;
}
export interface DuelAction {
    action_type: string;
    details: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DuelHistory {
    winner: Principal;
    actions: Array<DuelAction>;
    player1: Principal;
    player2: Principal;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Attribute {
    dark = "dark",
    fire = "fire",
    wind = "wind",
    earth = "earth",
    light = "light",
    divine = "divine",
    water = "water"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addUserCard(card_id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomCard(cardType: CardType, attribute: Attribute | null, rarity: bigint, art_blob: ExternalBlob | null, summon_sound: ExternalBlob | null, attack_sound: ExternalBlob | null, effect_sound: ExternalBlob | null): Promise<Card>;
    createDeck(name: string): Promise<void>;
    getAllCards(): Promise<Array<Card>>;
    getAllDuelHistory(caller_principal: Principal): Promise<Array<DuelHistory>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletedDuelHistory(): Promise<Array<DuelHistory>>;
    getCustomSounds(): Promise<Array<CustomSound>>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    initDuel(player2: Principal | null): Promise<{
        duel_id?: Principal;
        player1: Principal;
    }>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(username: string, difficulty: string): Promise<UserProfileView | null>;
    takeTurn(actions: Array<DuelAction>): Promise<void>;
}
import type { Attribute as _Attribute, Card as _Card, CardType as _CardType, CustomSound as _CustomSound, ExternalBlob as _ExternalBlob, UserProfileView as _UserProfileView, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addUserCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserCard(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomCard(arg0: CardType, arg1: Attribute | null, arg2: bigint, arg3: ExternalBlob | null, arg4: ExternalBlob | null, arg5: ExternalBlob | null, arg6: ExternalBlob | null): Promise<Card> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomCard(to_candid_CardType_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Card_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomCard(to_candid_CardType_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Card_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDeck(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeck(arg0);
            return result;
        }
    }
    async getAllCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCards();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCards();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDuelHistory(arg0: Principal): Promise<Array<DuelHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDuelHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDuelHistory(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedDuelHistory(): Promise<Array<DuelHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedDuelHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedDuelHistory();
            return result;
        }
    }
    async getCustomSounds(): Promise<Array<CustomSound>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomSounds();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomSounds();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initDuel(arg0: Principal | null): Promise<{
        duel_id?: Principal;
        player1: Principal;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initDuel(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDuel(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async takeTurn(arg0: Array<DuelAction>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.takeTurn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.takeTurn(arg0);
            return result;
        }
    }
}
function from_candid_Attribute_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attribute): Attribute {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CardType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardType): CardType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Card_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Promise<Card> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_CustomSound_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomSound): Promise<CustomSound> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_UserProfileView_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): Promise<UserProfileView> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attribute]): Attribute | null {
    return value.length === 0 ? null : from_candid_Attribute_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): Promise<UserProfileView | null> {
    return value.length === 0 ? null : await from_candid_UserProfileView_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    atk: [] | [bigint];
    def: [] | [bigint];
    monster_type: [] | [string];
    owner: [] | [Principal];
    summon_sound: [] | [_ExternalBlob];
    name: string;
    level_rank: [] | [bigint];
    attack_sound: [] | [_ExternalBlob];
    art_blob: [] | [_ExternalBlob];
    effect_text: [] | [string];
    effect_sound: [] | [_ExternalBlob];
    rarity: bigint;
    card_type: _CardType;
    is_custom: boolean;
    attribute: [] | [_Attribute];
}): Promise<{
    id: bigint;
    atk?: bigint;
    def?: bigint;
    monster_type?: string;
    owner?: Principal;
    summon_sound?: ExternalBlob;
    name: string;
    level_rank?: bigint;
    attack_sound?: ExternalBlob;
    art_blob?: ExternalBlob;
    effect_text?: string;
    effect_sound?: ExternalBlob;
    rarity: bigint;
    card_type: CardType;
    is_custom: boolean;
    attribute?: Attribute;
}> {
    return {
        id: value.id,
        atk: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.atk)),
        def: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.def)),
        monster_type: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.monster_type)),
        owner: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.owner)),
        summon_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.summon_sound)),
        name: value.name,
        level_rank: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.level_rank)),
        attack_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.attack_sound)),
        art_blob: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.art_blob)),
        effect_text: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.effect_text)),
        effect_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.effect_sound)),
        rarity: value.rarity,
        card_type: from_candid_CardType_n23(_uploadFile, _downloadFile, value.card_type),
        is_custom: value.is_custom,
        attribute: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.attribute))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    username: string;
    wallpaper: string;
    profile_picture: [] | [_ExternalBlob];
    difficulty: string;
    wins: bigint;
    losses: bigint;
    level: bigint;
    pack_count: bigint;
}): Promise<{
    xp: bigint;
    username: string;
    wallpaper: string;
    profile_picture?: ExternalBlob;
    difficulty: string;
    wins: bigint;
    losses: bigint;
    level: bigint;
    pack_count: bigint;
}> {
    return {
        xp: value.xp,
        username: value.username,
        wallpaper: value.wallpaper,
        profile_picture: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profile_picture)),
        difficulty: value.difficulty,
        wins: value.wins,
        losses: value.losses,
        level: value.level,
        pack_count: value.pack_count
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    victory_sound: [] | [_ExternalBlob];
    summon_sound: [] | [_ExternalBlob];
    attack_sound: [] | [_ExternalBlob];
    defeat_sound: [] | [_ExternalBlob];
    effect_sound: [] | [_ExternalBlob];
}): Promise<{
    victory_sound?: ExternalBlob;
    summon_sound?: ExternalBlob;
    attack_sound?: ExternalBlob;
    defeat_sound?: ExternalBlob;
    effect_sound?: ExternalBlob;
}> {
    return {
        victory_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.victory_sound)),
        summon_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.summon_sound)),
        attack_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.attack_sound)),
        defeat_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.defeat_sound)),
        effect_sound: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.effect_sound))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duel_id: [] | [Principal];
    player1: Principal;
}): {
    duel_id?: Principal;
    player1: Principal;
} {
    return {
        duel_id: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.duel_id)),
        player1: value.player1
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trap: null;
} | {
    spell: null;
} | {
    monster: {
        xyz: boolean;
        link: boolean;
        ritual: boolean;
        effect: boolean;
        fusion: boolean;
        synchro: boolean;
    };
}): {
    __kind__: "trap";
    trap: null;
} | {
    __kind__: "spell";
    spell: null;
} | {
    __kind__: "monster";
    monster: {
        xyz: boolean;
        link: boolean;
        ritual: boolean;
        effect: boolean;
        fusion: boolean;
        synchro: boolean;
    };
} {
    return "trap" in value ? {
        __kind__: "trap",
        trap: value.trap
    } : "spell" in value ? {
        __kind__: "spell",
        spell: value.spell
    } : "monster" in value ? {
        __kind__: "monster",
        monster: value.monster
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    fire: null;
} | {
    wind: null;
} | {
    earth: null;
} | {
    light: null;
} | {
    divine: null;
} | {
    water: null;
}): Attribute {
    return "dark" in value ? Attribute.dark : "fire" in value ? Attribute.fire : "wind" in value ? Attribute.wind : "earth" in value ? Attribute.earth : "light" in value ? Attribute.light : "divine" in value ? Attribute.divine : "water" in value ? Attribute.water : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Promise<Array<Card>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Card_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomSound>): Promise<Array<CustomSound>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CustomSound_n35(_uploadFile, _downloadFile, x)));
}
function to_candid_Attribute_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attribute): _Attribute {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CardType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardType): _CardType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attribute | null): [] | [_Attribute] {
    return value === null ? candid_none() : candid_some(to_candid_Attribute_n13(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "trap";
    trap: null;
} | {
    __kind__: "spell";
    spell: null;
} | {
    __kind__: "monster";
    monster: {
        xyz: boolean;
        link: boolean;
        ritual: boolean;
        effect: boolean;
        fusion: boolean;
        synchro: boolean;
    };
}): {
    trap: null;
} | {
    spell: null;
} | {
    monster: {
        xyz: boolean;
        link: boolean;
        ritual: boolean;
        effect: boolean;
        fusion: boolean;
        synchro: boolean;
    };
} {
    return value.__kind__ === "trap" ? {
        trap: value.trap
    } : value.__kind__ === "spell" ? {
        spell: value.spell
    } : value.__kind__ === "monster" ? {
        monster: value.monster
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attribute): {
    dark: null;
} | {
    fire: null;
} | {
    wind: null;
} | {
    earth: null;
} | {
    light: null;
} | {
    divine: null;
} | {
    water: null;
} {
    return value == Attribute.dark ? {
        dark: null
    } : value == Attribute.fire ? {
        fire: null
    } : value == Attribute.wind ? {
        wind: null
    } : value == Attribute.earth ? {
        earth: null
    } : value == Attribute.light ? {
        light: null
    } : value == Attribute.divine ? {
        divine: null
    } : value == Attribute.water ? {
        water: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
